# fly.toml app configuration file generated for intellisenseai on 2024-02-24T00:52:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'intellisenseai'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "app_data"
  destination = "/data"

